In [1]:
import os
import pandas as pd
import numpy as np
import shutil
from tqdm import tqdm
from pydub import AudioSegment

In [2]:
out_fld = '../data/GTZAN/data/'

In [35]:
genres_map = {
 'pop': 0,
 'metal': 1,
 'disco': 2,
 'blues': 3,
 'reggae': 4,
 'classical': 5,
 'rock': 6,
 'hiphop': 7,
 'country': 8,
 'jazz': 9
}

In [10]:
labels = []
for genre in tqdm(os.listdir('../data/GTZAN/genres/')):
    genre_path = '../data/GTZAN/genres/' + genre
    if os.path.isdir(genre_path):
        for file_name in os.listdir(genre_path):
            if '.DS_Store' in file_name:
                continue
            file_path = os.path.join(genre_path, file_name)
            elements = file_name.split('.')
            genre_id = genres_map.get(elements[0])

            track_id = "{:04d}".format(int(elements[1]))

            audio = AudioSegment.from_file(file_path, "au")
            audio.export(f"{out_fld}{genre_id}{track_id}.mp3", format="mp3")  

            labels.append([f'{genre_id}{track_id}', genre])
labels_df = pd.DataFrame(labels, columns=['track_id', 'genre'])

100%|██████████| 11/11 [06:28<00:00, 38.33s/it]

In [20]:
labels_df.index.sort_values()

Index(['0000', '0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008',
       '0009',
       ...
       '9090', '9091', '9092', '9093', '9094', '9095', '9096', '9097', '9098',
       '9099'],
      dtype='object', name='track_id', length=1000)

In [22]:
labels_df.to_csv('../data/GTZAN/labels.csv')

In [27]:
pd.read_csv('../data/fma_small/labels.csv')

       92885        Hip-Hop
0     122247        Hip-Hop
1     137500            Pop
2       3920           Folk
3      39488           Folk
4      62525   Experimental
5     125776           Rock
6       6675           Folk
7      94631           Folk
8     131924           Folk
9     120308           Folk
10    104779           Folk
11    137998           Folk
12    132117           Folk
13    112198           Folk
14    138355           Folk
15     38778           Folk
16    114231           Folk
17     11775            Pop
18     52635           Rock
19     43761           Rock
20     12061           Rock
21    125616   Experimental
22    127623           Rock
23    134077           Folk
24     72612           Folk
25     55807           Folk
26     11020           Rock
27     33050           Folk
28     43534   Experimental
29     59656           Folk
...      ...            ...
7532   16155            Pop
7533  121929            Pop
7534   25235            Pop
7535   58341           Rock
7536   42442  International
7537   56888  International
7538   51992  International
7539  120112  International
7540   32689  International
7541  122647  International
7542   99371  International
7543    7388  International
7544  108492  International
7545   69211  International
7546   80611  International
7547  138068  International
7548  140623  International
7549  134053  International
7550   25066  International
7551    4784   Instrumental
7552  125818        Hip-Hop
7553   49441        Hip-Hop
7554   36257        Hip-Hop
7555  133639        Hip-Hop
7556  126431        Hip-Hop
7557   85290        Hip-Hop
7558  129879           Rock
7559   96693           Rock
7560  107908           Rock
7561   28802           Rock

[7562 rows x 2 columns]

In [44]:
labels_df = pd.read_csv('../data/GTZAN/labels.csv')
labels_df.track_id = labels_df.track_id.apply(lambda x: '{:04d}.mp3'.format(x))

In [19]:
from sklearn.model_selection import train_test_split

In [53]:
train, test = train_test_split(labels_df, test_size=0.33, random_state=23)

In [54]:
train.head()

     track_id    genre
69   0051.mp3      pop
940  9098.mp3     jazz
14   0026.mp3      pop
866  8064.mp3  country
422  4065.mp3   reggae

In [55]:
train.to_csv('../data/GTZAN/train.csv', index=False)
test.to_csv('../data/GTZAN/test.csv', index=False)